let momQuotes = [
    "Everything I've learned that's worth knowing, I learned from my mother.",
    "Moms are the most beautiful beings in the world.",
    "No one has loved you like your mom and no one ever will. Her love is the purest of all.",
    "The highest compliment I could receive is that I've turned into my mother. I can only hope!",
    "When I became a mother, it was then I knew what was in my mom's heart.",
    "Nobody loves you like your mom. She's your best friend, your most honest critic, and your biggest fan all rolled into one.",
    "A mother's love does not set with the sun. It blankets you all through the night.",
    "My mother taught me more through her loving patience than I ever learned in school.",
    "Looking into my mother's eyes is like looking into the depths of the universe. May her strength, her love, her devotion, her fears, and her spirit be reflected in mine.",
    "No matter how old I get or how many children I have, I will always be my mother's child.",
    "It was your mom's turn to carry you when you were young. It's your turn to carry her when she grows old.",
    "No matter where I go, my mother's voice always brings me home.",
    "The road home is paved with a mother's love. There is always a path back into her arms.",
    "Mother, my greatest blessing is that you are mine. It is my honor to be called your daughter/son.",
    "The most perfect love is that between a mother and child. It is unending.",
    "Flowers in the field bow their blooms with awe in the presence of a mother. She is nature's blessing to all.",
    "The smell of my mom's perfume; the sight of her garden's flowers; the melody of her favorite song. All these things bring me closer to her even when we are far apart.",
    "I am nothing without my mother. She is the reason for everything I am and all that I will be.",
    "My fondest memory of childhood? My mother.",
    "A mother's tears can bring the world to its knees and her joy can cause celebration across the globe.",
    "Great moms like you inspire their children to do, see, and be more.",
    "Mom, you are my best friend and my mentor. I'm so proud to call you my mom!",
    "No one works harder than a mother. No one loves harder than a mother. No one can replace my mother!",
    "From the moment I was born, you showed me the way through this wonderful world. You taught me to see beauty in everything. I see the beauty in you, Mom.",
    "Every day is special when I get to spend it with my mom.",
    "A mother can hug you just with her smile.",
    "Wishes are granted in a mother's heart.",
    "So glad you're my mom!",
    "The sound of my mom's voice is the harmony to my melody.",
    "Moms are the biggest blooms in the bouquet of life.",
    "Loving my mother is my highest calling.",
    "Moms are the most underappreciated overachievers.",
    "No one is kinder or more caring than my mom.",
    "A mother who values her children have children who value her.",
    "Knowing my mother walks beside me gives me the strength to weather any storm.",
    "My mother is as strong as an oak that will never be felled.",
    "My mother is my best friend and my first hero. She never fails to lift me up when I am down.",
    "The soft touch from my mother belies her strength. Mom is a mighty woman who stands on her own two feet.",
    "With my mother behind me, I can do anything. She gives me strength.",
    "Moms do it all. They are counselors, teachers, bakers, managers, and cheerleaders, and they do it without breaking a sweat!",
    "It takes a strong woman to be a mom and an even stronger one to be MY mom!",
    "A mother's love is as soft as a bunny but as strong as an ox.",
    "It doesn't matter how old you get. Your mother's fierce love is always going to be there to hold you up.",
    "Mothers hold their children's burdens along with their hands. They are strong enough to do both.",
    "A mother does not send you out into the world unprepared. She send you out with her love, her prayers, and her strength to guide you through.",
    "The power of a mother's love is greater than any force on earth.",
    "Mom, you are the most courageous person I know. The perseverance you showed during [insert difficult memory here] showed me how deep your strength runs. I will never forget what you did.",
    "You'd never know the burdens on my mom's back, for she carries them all herself. She is fearless, independent, and strong. I hope to share her strength someday.",
    "Show me the strongest person in the world and I'll show you my mother. No one can compete!",
    "A mother's love will push you to the edge of the ocean while holding you above it. Her fearless strength keeps the wind in your sails.",
    "There's no safer haven than a mother's arms.",
    "The strongest lock in the world cannot keep love out of a mother's heart.",
    "Seeing the strength in my mom gives me hope for the future.",
    "I see my mom's strength reflected in all she does. If I only have half of her nerve and a hint of her wisdom, I will rejoice!",
    "Mom, you've been my rock. Thank you for showing me your steadfast strength.",
    "I don't need a knight in shining armor when my mother has given me her strength.",
    "Mom, thank you for being the first woman in my life. You'll always be the best one!",
    "You've helped me up when I fell, you've helped me learn when I struggled. You loved me more than a son deserves. I love you more than you realize!",
    "A son's love for his mother is eternal.",
    "A mother knows her son will leave her house, but he will never leave her heart's home.",
    "The bond between a son and his mother is stronger than a hurricane.",
    "Mom, I know I've given you plenty of headaches. But it didn't matter whether it was my broken arm or my move across the country, I knew you'd always head my way if I needed you.",
    "The guidance you gave me in life has only served to make me the man I am today.",
    "Behind a happy, loving man is a warm, caring mother.",
    "No one could [insert favorite activity with Mom] as well as you, Mom. Thank you for taking the time to teach me how to [do/say/play/make/create activity].",
    "I'm a better man because you were my mother.",
    "I may be your princess, but you are the greatest queen, Mom.",
    "Watching you has taught me more about being an independent woman than you'll ever know. Thank you for being my inspiration, Mom!",
    "You celebrated all of my successes and wept with all of my heartbreak. Mom, thank you for being the best mother a daughter could want.",
    "If every daughter had you as their mother, the world would be a better place. But I wouldn't want to share you!",
    "Mom, you showed me how to be a mother myself. I can only hope my children have a childhood as amazing as mine. I'm so glad you're their grandma!",
    "Being your daughter is the best thing that ever happened to me.",
    "A mother and daughter know each other's hearts like their own.",
    "The most extraordinary bond is between a mother and daughter. The thread connecting them stretches over distance and time, never to break.",
    "A great woman calls me daughter. I am humbled to be by her side in life.",
    "A daughter's love for her mother is only outshone by her mother's love for her.",
    "All that I am, or hope to be, I owe to my angel mother.",
    "No one else can be what you have been to me... You will always be the girl in my life..." ,
    "Mothers are a special gift sent from God above. They bless us with their nurturing and fill us with their love.",
    "To describe my mother would be to write about a hurricane in its perfect power. Or the climbing, falling colors of a rainbow.", 
    "I need you, I need you here, I need you now. I cannot do this alone. I need my Mommy, and dammit, I don't care who knows it.", 
    "A mother is she who can take the place of all others but whose place no one else can take.",
    "For the hand that rocks the cradle is the hand that rules the world.",
    "...The angels, whispering to one another, can find, among their burning terms of love, none so devotional as that of Mother...", 
    "One is a mother in order to love without beginning or end.",
    "There ought to be a hall of fame for mamas, creation's most unique and precious pearls.",
    "He didn't realize that love as powerful as your mother's for you leaves its own mark.",
]

function getRandomQuotes(){
    let  quote  = document.getElementById("display");
    let rand = Math.floor(momQuotes.length*Math.random());
    quote.innerText = `${momQuotes[rand]}`;

}
let button = document.getElementById("next");

button.addEventListener("click", () => getRandomQuotes());

document.onload  = getRandomQuotes()
